### ISSUE TITLE
commons-lang3 needs to be added as a dependency

### ISSUE THREAD

**Issue by hugo-lyppens** [jusjoken/GWeather#1]
I had to manually install commons-lang3 to get GWeather 3.1.1 to work on my SageTV and SageTVClient installations. Please fix the plugin to automatically pull in this dependency.

**Comment by jusjoken** [comment]
I just reviewed the code and it uses commons-lang ver 2.4 (which the plugin has a dependency included in the manifest) but has no dependency in the code for commons-lang3. I don't have time right now to test this out but when I do I will test a fresh install to see what's up.

**Comment by jusjoken** [comment]
Fixed with version 3.1.2.  The 3.1.1 version was built by another user (@ardyssey ) who was great to help out and get a version pushed out as I had not had time, however I believe it included an unintended dependency.  3.1.2 was build directly from the source with the changes @ardyssey implemented for OWM 3.0 and min/max for low/high temps.  I tested on a fresh install and no additional dependency should now be needed.

No changes were needed to this source as that dependency never existed in this source.
